### ISSUE TITLE
Upper limit on possible_k

### ISSUE THREAD

**Issue by DanielEWeeks** [OpenMendel/MendelIHT.jl#52]
I was trying a small toy example based on your "Sparse linear regression" instructions, and mistakenly set the upper limit for `possible_k` to a value larger than the number of columns of `x`, and this led to kind of a long error message that took me a while to properly understand.  

So consider adding an informative error check if someone inadvertently also makes this mistake.

```
possible_k = collect(0:9)
mses = cv_iht(y, x, path=possible_k)
```

Also, in your "Sparse linear regression" and "Sparse logistic regression" examples, consider removing the embedded "julia >" prompts, so it would be easier to paste this example code into a Julia session.

Thank you,
Dan

**Comment by biona001** [comment]
Dear Dan,

Thank you for the suggestion! We will incorporate them into the next minor release `v1.4.8` once unit tests pass. You can update to the latest code via 
```julia
using Pkg
pkg"up MendelIHT"
```
