### ISSUE TITLE
AppVeyor not installing SnpArrays correctly

### ISSUE THREAD

**Issue by kose-y** [OpenMendel/MendelIHT.jl#9]
Related to #6. 
It seems like the build on Appveyor is failing because it could not find the correct version of SnpArrays.jl. 
https://ci.appveyor.com/project/biona001/mendeliht-jl
This [script](https://github.com/biona001/MendelIHT.jl/blob/master/appveyor.yml) should be modified to install SnpArrays.jl directly from github. 

Note: It will still fail to build on AppVeyor even after the fix, as SnpArrays.jl currently fails on AppVeyor.

**Comment by biona001** [comment]
6af1597 fixed this issue
